version: "3.8"
services:
  fastapi:
    build: .
    container_name: ai_call_center
    ports:
      - "8000:8000"
    env_file:
      - .env # Mount the .env file
    volumes:
      - .:/app

volumes:
  mongo_data:
