;=== Voicebot Extension Configuration ===
; Thêm vào file pjsip.conf

;=== voicebot ===
[voicebot]
type=aor
max_contacts=5
remove_existing=yes
qualify_frequency=30

[voicebot]
type=auth
auth_type=userpass
username=voicebot
password=1234

[voicebot]
type=endpoint
aors=voicebot
auth=voicebot
context=internal
dtls_auto_generate_cert=yes
webrtc=yes
disallow=all
allow=opus,ulaw
transport=transport-wss
