name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set deploy variables
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ "$BRANCH" = "main" ]; then
            echo "IMAGE_TAG=latest"  >> $GITHUB_ENV
            echo "PORT=8000"         >> $GITHUB_ENV
            echo "CONTAINER=app-prod">> $GITHUB_ENV
          else
            echo "IMAGE_TAG=staging" >> $GITHUB_ENV
            echo "PORT=8001"         >> $GITHUB_ENV
            echo "CONTAINER=app-stg" >> $GITHUB_ENV
          fi

      - name: Checkout (for workflow refs)
        uses: actions/checkout@v3

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << 'EOF'
            set -e
            # stop & remove old container
            docker rm -f $CONTAINER || true
            # pull latest image
            docker pull npt1601/ai-call-center:$IMAGE_TAG
            # run new container, load .env from host
            docker run -d \
              --env-file /var/www/myapp/.env \
              -p $PORT:8000 \
              --name $CONTAINER \
              npt1601/ai-call-center:$IMAGE_TAG
          EOF
